name: Checkout

on:
  push:

jobs:
  build:
    strategy:
        matrix:
          os: [windows-latest, ubuntu-latest, macOS-latest]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
